config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

  resources :jams, only: [:show, :new, :create, :update]
  root to: "jams#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jam.rb
class Jam < ApplicationRecord
	has_attached_file :cover_image, styles: { default: "600x600", thumb: "100x100" }, default_url: "/images/:style/missing.png"
	attr_reader :cover_image_remote_url
	
	enum  status: [ :downloading, :chopping, :compressing, :uploading, :cleaning_up, :done, :deleted, :error, :applying_metadata ]
	enum	audio_format: [ :mp3, :wav ]
	has_many :tracks
	accepts_nested_attributes_for :tracks
	belongs_to :user

	mount_uploader :jam_zip_upload, JamUploader

	scope :to_delete, -> { where("uploaded_at < ?", Time.zone.now - 1).where(upload_deleted_at: nil) }

	validates :youtube_url, format: { with: Constants::YOUTUBE_URL_REGEX }
	validates :youtube_url, :youtube_id, :youtube_title, presence: true
	validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\z/
	validates_presence_of :tracks

	def cover_image_remote_url=(url_value)
		self.cover_image = URI.parse(url_value)
		@cover_image_remote_url = url_value
	end

	def download_root_path
		File.join(Constants::DOWNLOAD_DIR, id.to_s)
	end

	def download_dir_path
		File.join(download_root_path, id.to_s)
	end

	def tar_path
		File.join(download_root_path, "#{PathSanitizer.sanitize(youtube_title)}.tar.gz")
	end

	def youtube_dl_path
		"\"#{download_dir_path}/#{id}.\%\%(ext)\""
	end

	def raw_audio_path
		File.join(download_dir_path, "#{id}.wav")
	end
end

app/models/track.rb
class Track < ApplicationRecord
	belongs_to :jam
	validates_presence_of :jam
	validates :start_time, :end_time, :name, :track_number, presence: true
	validates :start_time, :end_time, format: { with: /\A(\d{1,2}:\d{1,2}(?::\d{1,2})?)\z/, message: 'must use HH:MM:SS format'}
	validates :name, uniqueness: { scope: :jam }

	def track_path(audio_format: jam.audio_format)
		File.join(jam.download_dir_path, "#{PathSanitizer.sanitize(name)}.#{audio_format}")
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :jams

	validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
end

app/models/video.rb
class Video < Yt::Video
	attr_accessor :youtube_url
	
	def initialize(youtube_url)		
		@youtube_url = youtube_url
		super(id: content_id)
	end

	def content_id
		@_content_id ||= Rack::Utils.parse_query(@youtube_url.split("?")[-1])["v"]
	end

	def track_suggestions
		parse_text(description) || default_track_suggestion
	end

	private

		def default_track_suggestion
			[{ start_time: "00:00", name: title, end_time: end_time, track_number: 1 }]
		end

		def end_time
			Time.at(duration).utc.strftime("%H:%M:%S")
		end

		def parse_text(text)
			time_regex = /[\[\(]?(\d{1,2}:\d{1,2}(?::\d{1,2})?)[[\]\)]]?/
			return unless text.scan(time_regex).size > 1
			tracks = text.split("\n").map { |l| l =~ time_regex ? { start_time: l.match(time_regex).captures.first, name: l.gsub(time_regex, '').strip} : nil }.compact
			tracks.each_with_index do |t,i|
				track_end_time = t == tracks.last ? end_time : tracks[i+1][:start_time]
				t[:end_time] = track_end_time
				t[:track_number] = i + 1
			end
			tracks
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_raven_context

  private

  	def set_raven_context
  		Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  	end
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController

  def show
    render locals: { jam: jam }
  end

  def new
    render locals: { jam: Jam.new } and return unless youtube_url
    unless youtube_url =~ Constants::YOUTUBE_URL_REGEX
      flash[:alert] = I18n.t("activerecord.errors.models.jam.attributes.youtube_url")
      render locals: { jam: Jam.new } and return 
    end
    jam = Jam.new(
      youtube_url: youtube_url,
      youtube_id: video.content_id,
      youtube_title: video.title,
      )
    jam.cover_image_remote_url = video.thumbnail_url(size = :medium)
    video.track_suggestions.each { |t| jam.tracks.build(t) }
    render locals: { jam: jam || Jam.new(youtube_url) }
  end

  def create
    jam = Jam.new(jam_params)
    jam.cover_image_remote_url = jam_params[:cover_image_remote_url]
    if jam.save
      ChopJamJob.perform_later(jam)
      redirect_to jam
    else
      render :new, locals: { jam: jam }
    end
  rescue ActiveRecord::RecordNotUnique
    jam.errors.add(:tracks, :unique)
    jam.tracks.group_by(&:name).select { |k,v| v.length > 1 }.each_value { |v| v.each { |t| t.errors.add(:name, :unique) } } 
    render :new, locals: { jam: jam }    
  end

  def update
    user = User.find_or_create_by(email: user_params[:email])
    jam.user = user
    respond_to do |format|
      if jam.save
        format.json { render json: { message: I18n.t('email.sent', email: user.email) } }
      else
        format.json { head :unprocessible_entity }
      end
    end
  end

  private

    def jam
      @_jam ||= Jam.find(params[:id])
    end

    def jam_params
      params.require(:jam).permit(:artist, :cover_image_remote_url, :youtube_url, :youtube_title, :youtube_id, tracks_attributes: [:track_number, :start_time, :name, :end_time])
    end

    def user_params
      params.require(:jam).permit(user: [:email])&.[](:user)
    end

    def youtube_url
      params[:jam_params]&.[](:content_url)
    end

    def video
      @_video ||= Video.new(youtube_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def svg(name)
	  file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
		File.exists?(file_path) ? File.read(file_path).html_safe : '(not found)'
	end
end

app/helpers/jams_helper.rb
module JamsHelper
end

app/views/jams/_form.html.haml
- if jam.errors.any?
  .alert.alert-danger
    - jam.errors.full_messages.uniq.each do |message|
      %p=message

= form_with(model: jam, local: true) do |f|
  = f.hidden_field :youtube_url
  = f.hidden_field :youtube_id
  .row
    .col-xs-12.col-md-6.cover-image
      = image_tag jam.cover_image_remote_url, class: "pull-left"
    = f.hidden_field :cover_image_remote_url
    .col-xs-12.col-md-6.album-meta
      = f.text_field :youtube_title
      = f.text_field :artist, placeholder: 'Artist'
  %hr
  .table-container
    %table.table#tracks-table
      = f.fields_for :tracks do |tracks_form|
        %tr
          %td.track-no
            = tracks_form.text_field :track_number
          %td.time-field
            = tracks_form.text_field :start_time
          %td.time-field
            = tracks_form.text_field :end_time
          %td.name-field
            = tracks_form.text_field :name
          %td
            %button.remove-track.glyphicon.glyphicon-remove.pull-right

  .col-md-6.text-center
    %button.btn.form-button#add-track=t('components.album.add_track')
  .col-md-6
    = f.button t('components.album.create'), type: :submit, class: "form-button btn"

app/views/jams/_url_form.html.haml
.url-form
	%h3="Enter Youtube Video URL"
	= form_for(:jam_params, url: new_jam_path, method: :get) do |f|
		.input-group.input-group-lg
			= f.text_field :content_url, { class: "form-control", placeholder: "e.g.: https://www.youtube.com/watch?v=Gn2yttLwYlo" }
			.input-group-btn
				= f.button 'Go', type: :submit, class: 'btn btn-success'
%p
	=t('info.youtube_track_list')
%a{ href: new_jam_path(jam_params: { content_url: "https://www.youtube.com/watch?v=Gn2yttLwYlo" }) }=t('info.see_example')

app/views/jams/edit.html.haml
%h1="Editing Jam"

= render 'form', jam: @jam

= link_to 'Show', @jam
= link_to 'Back', jams_path

app/views/jams/index.html.haml
%p#notice>= notice

= form_for(:jam_params, url: new_jam_path, method: :get) do |f|
  .input-group
    = f.text_field :content_url, { class: "form-control", placeholder: "e.g.: https://www.youtube.com/watch?v=VlQV2kFXDb8&"}
    .input-group-btn
      = f.button 'Go', type: :submit, class: 'btn btn-success'
%h1
  Other Jams
  %table
    %thead>
      %tr>
        %th

    %tbody>
      - jams.each do |jam|
        %tr
          %td= jam.youtube_title
          %td= link_to 'Show', jam
          %td= link_to 'Edit', edit_jam_path(jam)
          %td= link_to 'Destroy', jam, method: :delete, data: { confirm: 'Are you sure?' }

%br>

app/views/jams/new.html.haml
= render 'shared/flash'
- if jam.youtube_id
	= render 'form', jam: jam
- else
	= render 'url_form', jam: jam

app/views/jams/show.html.haml
.row
	.col-xs-12.col-md-6.cover-image
		= image_tag jam.cover_image, class: "pull-left"
	.col-xs-12.col-md-6.album-meta
		.album-meta
			%h5= jam.youtube_title
%hr
.table-container
	%table.table#tracks-table
		-jam.tracks.order(track_number: :asc).each do |t|
			%tr
				%td=t.track_number
				%td=t.start_time
				%td=t.end_time
				%td.name-field=t.name

#status-container
	- if jam.jam_zip_upload.url
		%a.btn.form-button{ href: jam.jam_zip_upload.url }=t('components.album.download')
	- else
		#status-display{ data: { jam_id: jam.id } }
			#loading-svg=svg 'loading'
			%p=I18n.t("statuses.#{jam.status.presence || 'queued'}")
#user-info
	#user-notice
		-if jam.user
			.alert.alert-success
				= t('email.sent', email: jam.user.email)
	#email-form-containter{ style: "display:#{jam.user ? 'none' : ''}" }			
		= form_for(jam, remote: true, html: { id: "email-form" }, format: :json ) do |f|
			= f.fields_for :user do |u|
				.input-group
					= u.text_field(:email, class: "form-control")
					.input-group-btn
						= u.button 'Go', type: :submit, class: 'btn btn-success', id: "user-email"

app/views/layouts/application.html.haml
%html
	%head
		= csrf_meta_tags
		%meta{name: "viewport", content: "width=device-width, initial-scale=1"}
		%meta{property: "og:title", content: "JamChop"}
		%meta{property: "og:image", content: image_url("og-img.png")}
		%meta{property: "og:description", content: "Turn youtube videos into customized mp3 albums with ease."}
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

		- if Rails.env.production?			
			%script{ src: "https://www.googletagmanager.com/gtag/js?id=UA-106993436-1" }
			%script
				window.dataLayer = window.dataLayer || [];
				function gtag(){dataLayer.push(arguments)};
				gtag('js', new Date());

				gtag('config', 'UA-106993436-1');
		%title
			JamChop

	%body
		= render partial: 'shared/header'
		.col-md-8.col-md-offset-2.col-xs-12{align: "center"}
			= yield

app/views/shared/_flash.html.haml
- if flash.any?
	.alert.alert-danger
		%p=flash.alert

app/views/shared/_header.html.haml
%nav.nav.navbar-inverse.bg-faded
	%a.navbar-brand{href: root_path} JamChop!